name: Build and Release

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  build_x86_64:
    name: Build x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl make musl-tools musl-dev
          sudo update-ca-certificates

      - name: Check commit message
        id: check_message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1)
          if [[ "$COMMIT_MESSAGE" != *"#major"* ]] && [[ "$COMMIT_MESSAGE" != *"#minor"* ]] && [[ "$COMMIT_MESSAGE" != *"#patch"* ]]; then
            echo "The latest commit message does not include a version bump keyword. Defaulting to patch version bump."
            echo "VERSION_BUMP=patch" >> $GITHUB_ENV
          else
            echo "VERSION_BUMP=${{ github.event.inputs.versionBump }}" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.VERSION_BUMP }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary-x86_64
          path: target/x86_64-unknown-linux-musl/release/my-binary

  build_aarch64:
    name: Build aarch64
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            brew install perl make musl clang llvm cmake

      - name: Set environment variables
        run: |
          echo "CC_aarch64_unknown_linux_musl=clang" >> $GITHUB_ENV
          echo "AR_aarch64_unknown_linux_musl=llvm-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS=-Clink-self-contained=yes -Clinker=rust-lld -Clink-args=-L/usr/lib/x86_64-linux-musl/" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-unknown-linux-musl

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-unknown-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary-aarch64
          path: target/aarch64-unknown-linux-musl/release/my-binary

  release:
    needs: [build_x86_64, build_aarch64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Package artifacts
        run: |
          mkdir -p release
          mv artifacts/my-binary-x86_64/my-binary release/my-binary-x86_64
          mv artifacts/my-binary-aarch64/my-binary release/my-binary-aarch64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset x86_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/my-binary-x86_64
          asset_name: my-binary-x86_64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/my-binary-aarch64
          asset_name: my-binary-aarch64
          asset_content_type: application/octet-stream